defaults:
  - airl_run_base
  - environment: gym_env
  - airl/reward_net: shaped
  - airl/gen_algo: ppo
  - evaluation: default_evaluation
  - airl/demonstrations: generated
  - airl/demonstrations/expert_policy: random
  - override hydra/sweeper: optuna
  - _self_

total_timesteps: 40000
checkpoint_interval: 1

airl:
  demo_batch_size: 128
  demonstrations:
    total_timesteps: 10
  allow_variable_horizon: true

hydra:
  mode: MULTIRUN
  sweeper:
    params:
      environment: cartpole,pendulum
      airl/reward_net: basic,shaped,small_ensemble
